version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '!@#M3t4tr0n'
      MYSQL_DATABASE: ecoreDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecoreDB?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '!@#M3t4tr0n'
volumes:
  mysql-data: